-- MySQL Script generated by MySQL Workbench
-- Fri Jun 23 20:38:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema evolucao_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema evolucao_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `evolucao_bd` DEFAULT CHARACTER SET utf8 ;
USE `evolucao_bd` ;

-- -----------------------------------------------------
-- Table `evolucao_bd`.`Personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucao_bd`.`Personal` (
  `idPersonal` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Cpf` VARCHAR(45) NOT NULL,
  `CREF` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Salario` FLOAT NOT NULL,
  PRIMARY KEY (`idPersonal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evolucao_bd`.`Mensalidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucao_bd`.`Mensalidade` (
  `idMensalidade` INT NOT NULL AUTO_INCREMENT,
  `Valor_mensalidade` FLOAT NOT NULL,
  `Data_Pagamento` DATE NOT NULL,
  PRIMARY KEY (`idMensalidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evolucao_bd`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucao_bd`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Cpf` VARCHAR(45) NOT NULL,
  `n_celular` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Personal_idPersonal` INT NOT NULL,
  `Mensalidade_idMensalidade` INT NULL,
  PRIMARY KEY (`idUsuario`, `Personal_idPersonal`),
  INDEX `fk_Usuario_Personal1_idx` (`Personal_idPersonal` ASC) VISIBLE,
  INDEX `fk_Usuario_Mensalidade1_idx` (`Mensalidade_idMensalidade` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Personal1`
    FOREIGN KEY (`Personal_idPersonal`)
    REFERENCES `evolucao_bd`.`Personal` (`idPersonal`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Usuario_Mensalidade1`
    FOREIGN KEY (`Mensalidade_idMensalidade`)
    REFERENCES `evolucao_bd`.`Mensalidade` (`idMensalidade`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evolucao_bd`.`Treinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucao_bd`.`Treinos` (
  `idTreinos` INT NOT NULL AUTO_INCREMENT,
  `Exercicios` VARCHAR(45) NULL,
  `nome_treino` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTreinos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evolucao_bd`.`Rotina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucao_bd`.`Rotina` (
  `idRotina` INT NOT NULL AUTO_INCREMENT,
  `Nome_rotina` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Personal_idPersonal` INT NOT NULL,
  PRIMARY KEY (`idRotina`, `Usuario_idUsuario`, `Personal_idPersonal`),
  INDEX `fk_Rotina_Usuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Rotina_Personal1_idx` (`Personal_idPersonal` ASC) VISIBLE,
  CONSTRAINT `fk_Rotina_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `evolucao_bd`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Rotina_Personal1`
    FOREIGN KEY (`Personal_idPersonal`)
    REFERENCES `evolucao_bd`.`Personal` (`idPersonal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evolucao_bd`.`Treinos_has_Rotina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evolucao_bd`.`Treinos_has_Rotina` (
  `Treinos_idTreinos` INT NOT NULL,
  `Rotina_idRotina` INT NOT NULL,
  `Rotina_Usuario_idUsuario` INT NOT NULL,
  `Series` VARCHAR(45) NULL,
  `repeticoes` VARCHAR(45) NULL,
  INDEX `fk_Treinos_has_Rotina_Rotina1_idx` (`Rotina_idRotina` ASC, `Rotina_Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Treinos_has_Rotina_Treinos1_idx` (`Treinos_idTreinos` ASC) VISIBLE,
  CONSTRAINT `fk_Treinos_has_Rotina_Treinos1`
    FOREIGN KEY (`Treinos_idTreinos`)
    REFERENCES `evolucao_bd`.`Treinos` (`idTreinos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Treinos_has_Rotina_Rotina1`
    FOREIGN KEY (`Rotina_idRotina` , `Rotina_Usuario_idUsuario`)
    REFERENCES `evolucao_bd`.`Rotina` (`idRotina` , `Usuario_idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
